---
title: "COGS 219 Behavioral Study"
author: "James Mannix"
format: html
editor: visual
---

```{r}
#| label: Load R libraries
#| echo: false # hides code in rendered doc
#| message: false # hides messages in code

library(osfr)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(ez)
library(rjson)
library(jsonlite)
```

```{r}
#| label: Load the data from OSF
#| include: false # hides data objects generated by code
#| echo: false

osf_retrieve_node("x38yn") %>%
  osf_ls_files(n_max = "Inf") %>%
  osf_download(path="data/", conflicts="skip")
```

```{r}
#| label: Concatenate data files into one file
#| echo: false

files <- list.files(path = "data/", full.names = T)

data <- lapply(files, fromJSON) %>% 
  bind_rows()
```

```{r}
#| label: Clean up data frame
#| echo: false

data.clean <- data %>% 
  select(-c("success", "timeout", "failed_images", "failed_audio", "failed_video", "trial_type", "trial_index", "time_elapsed", "internal_node_id", "study_id", "session_id", "stimulus")) %>% 
  filter(phase == "test", 
         task == "choose") %>% 
  pivot_longer(c("left_upvote", "right_upvote"), 
               names_to = "img_pos", values_to = "upvotes")
```

```{r}
#| label: Upvote graph!
#| echo: false

data.clean <- data.clean %>% 
  mutate(revealed = ifelse(((response == "arrowleft" && img_pos == "left_upvote") | (response == "arrowright" && img_pos == "right_upvote")), TRUE, FALSE))

```

## Methods

```{r}
#| label: Count the number of subjects
#| echo: false

n.subjects <- data %>%
  pull(subject_id) %>%
  unique() %>%
  length()
```

### Participants

`r n.subjects` Prolific members participated in the study.

### Procedure

Reddit and stuff.

### 
